language: C
# secret keys to upload results to google code
env:
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y libgd2-xpm ia32-libs ia32-libs-multiarch p7zip > /dev/null
  - wget -q --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86.bin -O ndk.bin
  - md5sum ndk.bin | grep 70ed6d8c34e7e620c145b791e8eeef89
  - 7zr x ndk.bin > /dev/null
  - export ANDROID_HOME=$(pwd)/android-sdk-linux
script:
  - PROFILER_VERSION=$(git describe)
  - make
  - make check
  - make srcdist dist VERSION="$PROFILER_VERSION"
